<a href="https://colab.research.google.com/github/ancestor9/24_fall_Big-Data-Processing-coding-/blob/main/09_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

## 데이터 타입

* series
* dataframe

In [ ]:
# module import
import pandas as pd
import numpy as np
pd

<module 'pandas' from 'C:\\Users\\sir95\\anaconda3\\envs\\cpu_env\\lib\\site-packages\\pandas\\__init__.py'>

In [ ]:
s1 = pd.Series([10, 20, 30, 40, 50]) # sequential data
print("{}, \n==> type{}".format(s1, type(s1)))

0    10
1    20
2    30
3    40
4    50
dtype: int64, 
==> type<class 'pandas.core.series.Series'>


In [ ]:
s2 = pd.Series(np.arange(10)) # ndarray로도 만들 수 있음.
print("{}, \n==> type{}".format(s2, type(s2)))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32, 
==> type<class 'pandas.core.series.Series'>


## Series

* value + index
* 내부적으로 numpy 배열을 사용하므로 연산 속도가 빠르다.
* 데이터 타입 통일.
* `NaN` 값도 value로 가능.

In [ ]:
# 인덱스 확인
print(s1.index) # 인덱스를 range로 만듦.

RangeIndex(start=0, stop=5, step=1)


In [ ]:
# values 확인
print(f"{s1.values} ==> type:{type(s1.values)}")

[10 20 30 40 50] ==> type:<class 'numpy.ndarray'>


In [ ]:
# 데이터 타입
s3 = pd.Series(['a', 'b', True, 1, 2, 3])
print(s3) # type: object

0       a
1       b
2    True
3       1
4       2
5       3
dtype: object


In [ ]:
# 인덱스 설정 가능
s4 = pd.Series(['a', 'b', True, 1, 2, 3],
              index = ['hello', 'my', 'name', 'is', 'S', 'Eraser'])
print(s4)
print(s4.index)
print(s4.values)

hello        a
my           b
name      True
is           1
S            2
Eraser       3
dtype: object
Index(['hello', 'my', 'name', 'is', 'S', 'Eraser'], dtype='object')
['a' 'b' True 1 2 3]


In [ ]:
# dictionary로 series 생성
scores = {
    '국어': 100,
    '영어': 95,
    'Python': 70
}

scores_S = pd.Series(scores)
print(scores_S)
print("index", scores_S.index)
print("value", scores_S.values)

국어        100
영어         95
Python     70
dtype: int64
index Index(['국어', '영어', 'Python'], dtype='object')
value [100  95  70]


In [ ]:
# 날짜 인덱스
index_date = ['2020-01-01', '2020-01-02']
s4 = pd.Series([200, 195], index=index_date)
print(s4)
print(s4.index)

2020-01-01    200
2020-01-02    195
dtype: int64
Index(['2020-01-01', '2020-01-02'], dtype='object')


### date_range

 pandas에서 쉽게 날짜 인덱스를 생성할 수 있다.

* `freq` : 날짜 간격.

In [ ]:
# 날짜 인덱스 생성

date_1 = pd.date_range(start='2020-01-01', end='2020-01-07')
print(date_1)

# 형식이 달라도 가능
print(pd.date_range(start='20200101', end='20200107'))
print(pd.date_range(start='2020/01/01', end='2020/01/07'))
print(pd.date_range(start='01-01-2019', end='01.07.2019'))

# 기간 설정 : 일주일 기간
print(pd.date_range(start='20200101', periods=7))

# 간격 설정
print(pd.date_range(start='2020-01-01', periods=10, freq='2D')) # 이틀 간격
print(pd.date_range(start='2020-01-01', periods=10, freq='W')) # ???????????????????????????????????
print(pd.date_range(start='2020-01-01', periods=10, freq='W-Tue')) # ?????????????????
print(pd.date_range(start='2020-01-01', periods=10, freq='QS')) # 분기 시작점 10개
print(pd.date_range(start='2020-01-01', periods=10, freq='AS')) # 1년 시작

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2020-01-01', '2020-01-03', '2020-01-05', '2020-01-07',
               '2020-01-09', '2020-01-11', '

## dataframe

In [ ]:
# numpy의 array로 dataframe 생성

data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
index_date = pd.date_range('20200101', periods=3)
columns = ['A', 'B', 'C']
df = pd.DataFrame(data, index=index_date, columns=columns)
display(df)

A   B   C
2020-01-01  10  20  30
2020-01-02  40  50  60
2020-01-03  70  80  90

In [ ]:
# dictionary로 dataframe 생성

table_data = {
    '연도': [2015, 2016, 2017, 2018, 2018],
    '지사': ['한국', '중국', '한국', '일본', '미국'],
    '고객 수': [100*(i+1) for i in range(2, 7)]
}

table_df = pd.DataFrame(table_data, columns=['고객 수', '지사', '연도']) # 컬럼 순서 변경 가능
display(table_df)

고객 수  지사    연도
0   300  한국  2015
1   400  중국  2016
2   500  한국  2017
3   600  일본  2018
4   700  미국  2018

In [ ]:
# index, value, column
print(df.index)
print(df.values) # values: numpy 배열
print(df.columns)
print(table_df.index)
print(table_df.values)
print(table_df.columns)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03'], dtype='datetime64[ns]', freq='D')
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Index(['A', 'B', 'C'], dtype='object')
RangeIndex(start=0, stop=5, step=1)
[[300 '한국' 2015]
 [400 '중국' 2016]
 [500 '한국' 2017]
 [600 '일본' 2018]
 [700 '미국' 2018]]
Index(['고객 수', '지사', '연도'], dtype='object')


In [ ]:
# 전치
display(df.T)
display(table_df.T)

2020-01-01  2020-01-02  2020-01-03
A          10          40          70
B          20          50          80
C          30          60          90

0     1     2     3     4
고객 수   300   400   500   600   700
지사      한국    중국    한국    일본    미국
연도    2015  2016  2017  2018  2018

In [ ]:
# 접근
print(table_df['연도'])
print(table_df.지사)

0    2015
1    2016
2    2017
3    2018
4    2018
Name: 연도, dtype: int64
0    한국
1    중국
2    한국
3    일본
4    미국
Name: 지사, dtype: object


In [ ]:
# 연산
print(table_df.연도 + table_df['고객 수'])

0    2315
1    2416
2    2517
3    2618
4    2718
dtype: int64


In [ ]:
# 크기가 안 맞는 series 연산
arr = np.array([3, 5, 6, 7, 8, 9])
print(arr + 3) # broadcasting
s1 = pd.Series([0, 1, 2, 3, 5])
s2 = pd.Series([3, 5, 6, 7, 8, 9, 30])
print(s1 + s2) # NaN 반환

[ 6  8  9 10 11 12]
0     3.0
1     6.0
2     8.0
3    10.0
4    13.0
5     NaN
6     NaN
dtype: float64


In [ ]:
# 데이터프레임 연산

data1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
index_date = pd.date_range('20200101', periods=3)
columns = ['A', 'B', 'C']
df1 = pd.DataFrame(data1, index=index_date, columns=columns)
display(df1)


data2 = np.array([[100, 20, 3000], [40, 50, 60]])
index_date = pd.date_range('20200101', periods=2)
columns = ['A', 'B', 'C']
df2 = pd.DataFrame(data2, index=index_date, columns=columns)
display(df2)

display(df1 + df2) # 안 맞는 부분은 NaN값으로 반환

A   B   C
2020-01-01  10  20  30
2020-01-02  40  50  60
2020-01-03  70  80  90

A   B     C
2020-01-01  100  20  3000
2020-01-02   40  50    60

A      B       C
2020-01-01  110.0   40.0  3030.0
2020-01-02   80.0  100.0   120.0
2020-01-03    NaN    NaN     NaN

In [ ]:
# 데이터프레임 요소 선택

ktx_data = {
    '경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41286, 324270],
    '호남선 KTX': [7313, 6967, 6873, 4131, 42302, 1386, 3270],
    '경전선 KTX': [390, 896, 4205, 4321, 702, 486, 324270],
    '전라선 KTX': [0, 16, 15, 521, 4, 56, 324270],
    '동해선 KTX': [np.nan, np.nan, np.nan, np.nan, 13579, np.nan, 324270], # nan있으면 값은 실수로 맞춰진다.
}

col_list = ['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX']
idx_list = [str(2011+i) for i in range(0, 7)]

ktx_df = pd.DataFrame(ktx_data, columns=col_list, index=idx_list)
display(ktx_df)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX   동해선 KTX
2011    39060     7313      390        0       NaN
2012    39896     6967      896       16       NaN
2013    42005     6873     4205       15       NaN
2014    43621     4131     4321      521       NaN
2015    41702    42302      702        4   13579.0
2016    41286     1386      486       56       NaN
2017   324270     3270   324270   324270  324270.0

In [ ]:
# 연산
print(ktx_df.sum(axis=1))
print(ktx_df.mean(axis=0))

2011      46763.0
2012      47775.0
2013      53098.0
2014      52594.0
2015      98289.0
2016      43214.0
2017    1300350.0
dtype: float64
경부선 KTX     81691.428571
호남선 KTX     10320.285714
경전선 KTX     47895.714286
전라선 KTX     46411.714286
동해선 KTX    168924.500000
dtype: float64


In [ ]:
# 통계량
display(ktx_df.describe())
display(ktx_df.T.describe())

경부선 KTX       호남선 KTX        경전선 KTX        전라선 KTX  \
count       7.000000      7.000000       7.000000       7.000000   
mean    81691.428571  10320.285714   47895.714286   46411.714286   
std    106977.242960  14276.071865  121881.823743  122524.131918   
min     39060.000000   1386.000000     390.000000       0.000000   
25%     40591.000000   3700.500000     594.000000       9.500000   
50%     41702.000000   6873.000000     896.000000      16.000000   
75%     42813.000000   7140.000000    4263.000000     288.500000   
max    324270.000000  42302.000000  324270.000000  324270.000000   

             동해선 KTX  
count       2.000000  
mean   168924.500000  
std    219691.712954  
min     13579.000000  
25%     91251.750000  
50%    168924.500000  
75%    246597.250000  
max    324270.000000

2011          2012          2013          2014          2015  \
count      4.000000      4.000000      4.000000      4.000000      5.000000   
mean   11690.750000  11943.750000  13274.500000  13148.500000  19657.800000   
std    18552.817636  18889.329622  19360.535487  20390.088074  21102.443963   
min        0.000000     16.000000     15.000000    521.000000      4.000000   
25%      292.500000    676.000000   3157.500000   3228.500000    702.000000   
50%     3851.500000   3931.500000   5539.000000   4226.000000  13579.000000   
75%    15249.750000  15199.250000  15656.000000  14146.000000  41702.000000   
max    39060.000000  39896.000000  42005.000000  43621.000000  42302.000000   

               2016           2017  
count      4.000000       5.000000  
mean   10803.500000  260070.000000  
std    20329.220964  143555.564155  
min       56.000000    3270.000000  
25%      378.500000  324270.000000  
50%      936.000000  324270.000000  
75%    11361.000000  324270.000000  
max    41286.000000  324270.000000

In [ ]:
# 첫 데이터, 마지막 데이터, 랜덤 추출
display(ktx_df.head())
display(ktx_df.tail(3))
display(ktx_df.sample(2))
display(ktx_df.T.sample(2))

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313      390        0      NaN
2012    39896     6967      896       16      NaN
2013    42005     6873     4205       15      NaN
2014    43621     4131     4321      521      NaN
2015    41702    42302      702        4  13579.0

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX   동해선 KTX
2015    41702    42302      702        4   13579.0
2016    41286     1386      486       56       NaN
2017   324270     3270   324270   324270  324270.0

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2014    43621     4131     4321      521      NaN
2011    39060     7313      390        0      NaN

2011     2012     2013     2014     2015     2016      2017
동해선 KTX      NaN      NaN      NaN      NaN  13579.0      NaN  324270.0
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41286.0  324270.0

In [ ]:
# 인덱싱, 슬라이싱
ktx_df[3:]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX   동해선 KTX
2014    43621     4131     4321      521       NaN
2015    41702    42302      702        4   13579.0
2016    41286     1386      486       56       NaN
2017   324270     3270   324270   324270  324270.0

### .loc, .iloc : 행, 열 순서

In [ ]:
# loc
print(ktx_df.loc['2011'])
print(ktx_df.T.loc['경부선 KTX'])
print(ktx_df.loc[:, ['경전선 KTX', '경부선 KTX']])
print(ktx_df.loc['2012':'2014', '경부선 KTX'])

경부선 KTX    39060.0
호남선 KTX     7313.0
경전선 KTX      390.0
전라선 KTX        0.0
동해선 KTX        NaN
Name: 2011, dtype: float64
2011     39060.0
2012     39896.0
2013     42005.0
2014     43621.0
2015     41702.0
2016     41286.0
2017    324270.0
Name: 경부선 KTX, dtype: float64
      경전선 KTX  경부선 KTX
2011      390    39060
2012      896    39896
2013     4205    42005
2014     4321    43621
2015      702    41702
2016      486    41286
2017   324270   324270
2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64


In [ ]:
# iloc
print(ktx_df.iloc[3])
print(ktx_df.iloc[2:4, 1:3])
print(ktx_df.iloc[3:, :])

경부선 KTX    43621.0
호남선 KTX     4131.0
경전선 KTX     4321.0
전라선 KTX      521.0
동해선 KTX        NaN
Name: 2014, dtype: float64
      호남선 KTX  경전선 KTX
2013     6873     4205
2014     4131     4321
      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX   동해선 KTX
2014    43621     4131     4321      521       NaN
2015    41702    42302      702        4   13579.0
2016    41286     1386      486       56       NaN
2017   324270     3270   324270   324270  324270.0


컬럼 순서를 바꿔서 들고오면 된다

In [ ]:
display(ktx_df[['동해선 KTX', '경전선 KTX', '전라선 KTX', '경부선 KTX', '호남선 KTX']])
display(ktx_df)

동해선 KTX  경전선 KTX  전라선 KTX  경부선 KTX  호남선 KTX
2011       NaN      390        0    39060     7313
2012       NaN      896       16    39896     6967
2013       NaN     4205       15    42005     6873
2014       NaN     4321      521    43621     4131
2015   13579.0      702        4    41702    42302
2016       NaN      486       56    41286     1386
2017  324270.0   324270   324270   324270     3270

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX   동해선 KTX
2011    39060     7313      390        0       NaN
2012    39896     6967      896       16       NaN
2013    42005     6873     4205       15       NaN
2014    43621     4131     4321      521       NaN
2015    41702    42302      702        4   13579.0
2016    41286     1386      486       56       NaN
2017   324270     3270   324270   324270  324270.0

## 결측치 처리

* 결측치 있는 컬럼 날리기
* 결측치 있는 행 날리기
* 평균값 등으로 채우기

In [ ]:
ktx_df_test_1 = ktx_df.copy() # 원본 복사
ktx_df_test_2 = ktx_df.copy()
ktx_df_test_3 = ktx_df.copy()

In [ ]:
# 1) 결측치 있는 컬럼 날리기
ktx_df_test_1.dropna(axis=1, inplace=True)
display(ktx_df_test_1)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX
2011    39060     7313      390        0
2012    39896     6967      896       16
2013    42005     6873     4205       15
2014    43621     4131     4321      521
2015    41702    42302      702        4
2016    41286     1386      486       56
2017   324270     3270   324270   324270

In [ ]:
# 2) 행 날리기
ktx_df_test_2.dropna(axis=0, inplace=True)
display(ktx_df_test_2)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX   동해선 KTX
2015    41702    42302      702        4   13579.0
2017   324270     3270   324270   324270  324270.0

In [ ]:
# 3) 결측치 채우기
ktx_df_test_3.fillna(ktx_df_test_3.mean(), inplace=True)
display(ktx_df_test_3)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX   동해선 KTX
2011    39060     7313      390        0  168924.5
2012    39896     6967      896       16  168924.5
2013    42005     6873     4205       15  168924.5
2014    43621     4131     4321      521  168924.5
2015    41702    42302      702        4   13579.0
2016    41286     1386      486       56  168924.5
2017   324270     3270   324270   324270  324270.0

## 데이터 통합

* append: 인덱스 중복 가능. 따라서 `ignore_index` 옵션 설정. 컬럼 방향으로 통합한다. 가로 방향.

In [ ]:
df1 = pd.DataFrame({
    'class 1': [95, 92, 98, 100],
    'class 2': [91, 93, 97, 99]
})

df2 = pd.DataFrame({
    'class 1': [911, 912],
    'class 2': [913, 914]
})

df3 = pd.DataFrame({
    'class 1': [1, 2]
})

In [ ]:
# append 사용
display(df1.append(df2))
display(df1.append(df2, ignore_index=True))
display(df2.append(df1))
display(df1.append(df3))

class 1  class 2
0       95       91
1       92       93
2       98       97
3      100       99
0      911      913
1      912      914

class 1  class 2
0       95       91
1       92       93
2       98       97
3      100       99
4      911      913
5      912      914

class 1  class 2
0      911      913
1      912      914
0       95       91
1       92       93
2       98       97
3      100       99

class 1  class 2
0       95     91.0
1       92     93.0
2       98     97.0
3      100     99.0
0        1      NaN
1        2      NaN

In [ ]:
# 가로 방향으로 통합하기 : 인덱스가 다르면 NaN으로 붙인다.
df4 = pd.DataFrame({
    'class 3': [93, 91, 95, 98]
})

df5 = pd.DataFrame({
    'class 4': [82, 91]
})
display(df4)
display(df1)
display(df1.join(df4))
display(df4.join(df1))
display(df4.join(df5))

class 3
0       93
1       91
2       95
3       98

class 1  class 2
0       95       91
1       92       93
2       98       97
3      100       99

class 1  class 2  class 3
0       95       91       93
1       92       93       91
2       98       97       95
3      100       99       98

class 3  class 1  class 2
0       93       95       91
1       91       92       93
2       95       98       97
3       98      100       99

class 3  class 4
0       93     82.0
1       91     91.0
2       95      NaN
3       98      NaN